# Generated by Django 4.2.4 on 2023-11-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminDB',
        ),
    ]
